CREATE TABLE IF NOT EXISTS users( 
user_id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
username varchar(255) NOT NULL UNIQUE,
email varchar(255) NOT NULL UNIQUE,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);